### ISSUE TITLE
API page 404 error

### ISSUE THREAD

**Issue by novalex** [SantiagoInteractive/mobilpay-card-gateway-for-woocommerce#2]
Hi,

I am trying to get mobilPay to work, but the API endpoint set by the plugin returns a 404 error. If I go to "http://my-site/wc-api/v2" it works, but "http://my-site/wc-api/WC_Mobilpay_Card" does not.

Any idea what I'm doing wrong? I searched for this problem and seems most people solved it by re-saving the permalinks or disabling Polylang, but neither of those works.

Cheers

**Comment by SantiagoInteractive** [comment]
Hi,

Try going, on the Admin Panel, to Settings -> Permalinks. On Default Settings radio group, select the "Post name" option. Save the changes.

If the problem is not fixed doing that, update your apache virtual host file because the AllowOverride was probably defaulted to None. Change it to: `AllowOverride All`.

Once you update this, and reload the Apache service, the API should work just fine.
